# Generated by Django 4.2.1 on 2023-07-10 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dosage', models.BigIntegerField()),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.reminder')),
            ],
        ),
    ]
