# Generated by Django 4.2.1 on 2023-07-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_usermethods_alter_reminder_options_profilepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='reminded',
            field=models.BooleanField(default=False),
        ),
    ]
