# Generated by Django 5.0.2 on 2024-02-19 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_reminder_reminded"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReminderType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reminder_type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("phone_call", "Phone Call"),
                            ("whatsapp", "WhatsApp"),
                        ],
                        default="email",
                        max_length=255,
                    ),
                ),
                (
                    "reminder",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="main.reminder"
                    ),
                ),
            ],
        ),
    ]
