# Generated by Django 5.0.2 on 2024-02-22 14:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_family_phone_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="reminder",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="reminder",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
