# Generated by Django 5.0.2 on 2024-03-04 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_alter_reminder_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="phone",
            name="code",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
