# Generated by Django 5.0.2 on 2024-03-07 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_phone_code"),
    ]

    operations = [
        migrations.RenameField(
            model_name="remindertype",
            old_name="reminder_type",
            new_name="type",
        ),
        migrations.RemoveField(
            model_name="reminder",
            name="time",
        ),
        migrations.AddField(
            model_name="remindertype",
            name="time",
            field=models.CharField(default="email", max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="remindertype",
            name="reminder",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.reminder"
            ),
        ),
    ]
