# Generated by Django 5.0.2 on 2024-03-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_rename_reminder_type_remindertype_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicine",
            name="dosage",
            field=models.CharField(max_length=255),
        ),
    ]
