# Generated by Django 5.0.2 on 2024-03-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_alter_medicine_dosage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reminder",
            name="title",
            field=models.CharField(default="Reminder", max_length=255),
            preserve_default=False,
        ),
    ]
