# Generated by Django 5.0.2 on 2024-03-11 18:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_alter_reminder_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="phone",
            name="sent_on",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
