# Generated by Django 5.0.2 on 2024-03-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_phone_sent_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phone",
            name="sent_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
